# Generated by Django 2.2.6 on 2019-11-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kec.StudentApplication'),
        ),
    ]
