# Generated by Django 2.2.6 on 2019-11-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kec', '0002_student_student_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='is_verify',
            new_name='is_verified',
        ),
    ]
